[package]
name = "ecomenu-printer"
version = "0.1.0"
build = "build.rs"
edition = "2021"

[dependencies]
printers = "2.1.2"
warp = "0.3.7"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
winres = "0.1.12"